### ISSUE TITLE
Pip install fails with ImportError: No module named Cython.Distutils

### ISSUE THREAD

**Issue by mhidas** [SciTools/cf-units#106]
`pip` doesn't seem able to install cf-units 2.0.1:

```
$ pip install cf-units
Collecting cf-units
  Using cached https://files.pythonhosted.org/packages/0c/01/32ac56ae9977baf05dca9b3c563c96118b4204dff5161ce5ec58113b649c/cf_units-2.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-hajt1m/cf-units/setup.py", line 6, in <module>
        from Cython.Distutils import build_ext
    ImportError: No module named Cython.Distutils
```

**Comment by pelson** [comment]
Thanks @mhidas. Naturally, ``pip install cython`` addresses the problem in the short term.
In the slightly longer-term, cf_units needs to implement it's setup.py a little more carefully to handle the case when cython is not already installed.

**Comment by pelson** [comment]
Relates to active discussion at https://github.com/pypa/setuptools/issues/1317#issuecomment-387702371. Looks like there will be a new approach in the pipeline over the next 18 months. In the meantime, I'll try getting our setup_requires working appropriately.

**Comment by pelson** [comment]
I've opened #108 to fix this. It should go into v2.0.2 if we decide to go down that approach.

Thanks for the report @mhidas.

**Comment by mhidas** [comment]
Thanks for the fix!

**Comment by hengqiali** [comment]
> Thanks @mhidas. Naturally, `pip install cython` addresses the problem in the short term.
> In the slightly longer-term, cf_units needs to implement it's setup.py a little more carefully to handle the case when cython is not already installed.

Thanks!It works for me to 'No Module named Cython'

**Comment by rzr** [comment]
or update pip as suggested at;

https://github.com/rzr/sense-hat-webthing/issues/3#issuecomment-626049913

https://github.com/CellProfiler/centrosome/issues/78

**Comment by MISSIVA20** [comment]
from Cython.Build import cythonize
ModuleNotFoundError: No module named 'Cython'
 i have this error, 
i make this cmd:
 pip install --upgrade cython     
and pip install cython 
python PythonAPI/setup.py build_ext install     
but i have same error do you have a solution
