### ISSUE TITLE
Package name rebrand

### ISSUE THREAD

**Issue by bjlittle** [SciTools/cf-units#112]
Proposing that we rebrand the package name to be `cf-units`, in light of the `nc-time-axis` rebrand.

**Comment by bjlittle** [comment]
Ping @pelson and @ocefpaf 

If there is appetite for this, then we'd need to consider the timing relative to `iris` version `2.1`...

**Comment by pelson** [comment]
Yep. Let's do it.

**Comment by pelson** [comment]
Please let's not delete old ``cf_units`` builds on conda-forge though - it means we can't re-install old versions easily and I consider it to be a negative step for reproducibility. Let people transition over to the ``cf-units`` name gradually.

**Comment by ocefpaf** [comment]
OK. I'm too late here :-(

> Please let's not delete old cf_units builds on conda-forge though

Even though I understand that we have a problem with people that will never get the new package b/c they won't find out about the rename. Unfortunately not everybody read release notes and watch GitHub :unamused:

**Comment by ocefpaf** [comment]
BTW, in the `nc_time_axis` package case, it was not removed, only moved to another label. Those who need 100% reproducibility can upgrade conda and install `nc_time_axis` with the new feature to pin a package from a channel/label.

**Comment by pelson** [comment]
> Unfortunately not everybody read release notes and watch GitHub 😒

Right, but we can push a new version of cf_units that simply raises an error. That way, existing build can remain (people can even pin to them), yet they get a pretty obvious error when they install cf_units anew (``ImportError: cf_units has been renamed to cf-units. Please conda install cf-units instead.``). Even better, we push Anaconda to actually allow "obsolete" type behaviour that you see in things like RPMs 😉.

**Comment by wjbenfold** [comment]
I met a user with cf_units and cf-units in the same environment today. I'd be in favour of pushing the obviously broken version to conda-forge if this hasn't been done

**Comment by ocefpaf** [comment]
Probably the best thing to do is to add an alias so those using cf_units will get the "new" cf-units too..
