### ISSUE TITLE
Custom html in README

### ISSUE THREAD

**Issue by DPeterK** [SciTools/cf-units#114]
I'm concerned at the nature of the custom html added to the README. As per my [review of the iris-grib README update](https://github.com/SciTools/iris-grib/pull/101#pullrequestreview-125614977), the changes have introduced accessibility problems and some questionable stylistic changes, arguably without adding anything beneficial to the README as was.

For the sake of having everything left-aligned, we could have an equivalent README written in pure markdown with no custom html. We should also drop the title-masquerading-as-hyperlink business and just include an explicit link to the cf-units docs in the README body - doing so will be much more accessible and clear.

Note: I do not disagree with updating the README to use markdown - that's definitely a positive step 👍

**Comment by pelson** [comment]
PRs welcome on this one. It will be hard for a change like this *not* to be subjective, and to be honest subjective changes are something that might never converge to a consensus within the development community.

For these reasons, closing this one out.
