### ISSUE TITLE
Rename the module?

### ISSUE THREAD

**Issue by rhattersley** [SciTools/cf-units#12]
We've [renamed the GitHub repo](https://github.com/SciTools/cf_units/issues/7), but we've not renamed the Python package/module name.

**Comment by ocefpaf** [comment]
I was thinking about that...  I am preparing a PR to rename `unit.py` to `cf_units.py`.

**Comment by ajdawson** [comment]
Just FYI, this might now looks like it is related to with cf-python and cf-plot (http://cfpython.bitbucket.org/ and http://www.met.reading.ac.uk/~andy/cfplot_sphinx/_build/html/). That is not necessarily a bad thing, doesn't really affect either Iris or those projects, but just in case you weren't aware of them.
