### ISSUE TITLE
AttributeError: 'module' object has no attribute 'date2num'

### ISSUE THREAD

**Issue by ocefpaf** [SciTools/cf-units#14]
While testing the docstrings I thing I found a bug here:

https://github.com/SciTools/cf_units/blob/master/units/unit.py#L637

`date2num` is in `netcdftime.utime.date2num` now, see https://github.com/Unidata/netcdf4-python/commit/4d482661b005ca82ac242c5cefc5b1652a236dc5

@rhattersley should I fix this or pin a netcdftime version?

**Comment by pelson** [comment]
I think we need to manage the two for a period. I'm afraid it is going to have to look something like:

```
try:
    import netcdftime.utime.date2num as date2num
except ImportError:
    import netcdftime.date2num as date2num
```

Unless a more elegant solution can be found.

**Comment by ocefpaf** [comment]
The `utime` class  exists in all version.  So I think we are good if we change the calls to  `netcdftime.date2num` for

``` python
t = netcdftime.utime('hours since 0001-01-01 00:00:00', calendar='standard')
t.date2num(datetime.strptime('3/14/15 9:26:53', '%m/%d/%y %H:%M:%S'))
```

I will test that as soon as #13 gets merged.
