### ISSUE TITLE
New CLA and relicensing cf-units from LGPL to BSD-3

### ISSUE THREAD

**Issue by pelson** [SciTools/cf-units#143]
I've been working through the details of relicensing cf-units (see also https://github.com/SciTools/scitools.org.uk/pull/209) from LGPL to BSD-3. The biggest driver for this comes from (often ill-informed) comments regarding the L in [L]GPL - I don't want to dwell on the accuracy the comments... it is what it is.

At the same time, re-licensing cf-units requires an update to the SciTools CLA (it explicitly names LGPL, as was the style in 2010...). Fortunately, I've also streamlined the CLA signing process (which used to be horribly clunky and manual, and is now replaced with a single web form).

I'm not a lawyer™️ , but my synopsis of the new CLA reads:

 * All contributions you make to cf-units remain your own (but you grant an irrevocable license for cf-units to use your contribution)
 * At any point in the future cf-units (and therefore your contributions) can be re-licensed to any other OSI approved license

(Please feel free to comment here if you believe I may be miss-representing it, it wasn't intentional!)

So with all of this said, please may I ask you to consider signing v4 of the SciTools CLA at https://scitools.org.uk/cla/v4/form:

 - [x] @ocefpaf 
 - [x] @pelson  
 - [x] @bjlittle 
 - [ ] @DPeterK 
 - [x] @cpelley
 - [ ] @djkirkham 
 - [x] @bekozi
 - [ ] @tv3141
 - [ ] @marqh 
 - [x] @rhattersley
 - [x] @QuLogic
 - [ ] @LukeC92 
 - [x] @kaedonkers
 - [x] @jeixav

Inevitably there will be some who have contributed to cf-units who are no longer contactable, or who are not prepared to sign the CLA. In this situation, we will have to asses the impact of either carrying the risk of having unlicensed contributions vs reverting those contributions from cf-units.

FWIW All Met Office contributions are already made under the terms of the v4 CLA, but it would significantly help with transparency if all Met Office contributors could sign the new CLA also (please).

**Comment by pelson** [comment]
Whilst there are still a number of names on the list, the the ones that we don't already have institutional CLAs for are @bekozi and @QuLogic. All others will be prohibited from contributing new changes until a v4 of the CLA is on file, but aren't blocking a re-license.

I don't want to put pressure on you both, but if you are willing to sign the document I'd be really appreciative (please feel free to contact me offline if you have any concerns / can't sign).

**Comment by ESadek-MO** [comment]
Closed by #331.
