### ISSUE TITLE
Test failure on Windows + Python2.7 - test_read_xml_invalid_path

### ISSUE THREAD

**Issue by pelson** [SciTools/cf-units#148]
https://github.com/conda-forge/cf_units-feedstock/pull/23#issuecomment-462233001 highlighted that there appears to be a genuine issue with cf-units (or maybe even udunits itself) not passing the same exception code back from an invalid call.

We should really try to add some Windows testing to our matrix to catch this before release (perhaps via [azure pipelines](https://azure.microsoft.com/en-gb/services/devops/pipelines/) (as is done on conda-forge).

**Comment by rcomer** [comment]
This issue appears to be specific to python 2.7, which we dropped at #157.  So I think there is nothing more to do here.
