### ISSUE TITLE
`is_vertical`?

### ISSUE THREAD

**Issue by ocefpaf** [SciTools/cf-units#15]
`is_vertical` returns True for distances.  That is the correct behavior, but the name is not all that intuitive.

**Comment by pelson** [comment]
It might be safest to get a tagged release of cf_units from which Iris can depend before we change the functionality too much. That way the work to get iris using cf_units rather than iris.units should be simpler.

What do you think?

**Comment by ajdawson** [comment]
True, but on the other hand if the suggestion is a change to the public API of cf_units (a name change) then perhaps it should go in before a tagged release.

**Comment by ocefpaf** [comment]
I will avoid changes to the Public API until we can tag a release, and I will tag a release as soon as I finish #14, #12, #3, #2.

Sounds like a plan?

**Comment by pelson** [comment]
> Sounds like a plan?

:+1: from me. I can see @ajdawson's point, so perhaps we should tag 0.1 in the Iris "unchanged" form, and then look to iterate quickly and if necessary move on to v1.x within a release or two.

**Comment by pelson** [comment]
Ping - is this still something you want to investigate @ocefpaf?

**Comment by ocefpaf** [comment]
I would not rename it and Ido not believe we can return `True` for vertical units based only on the units.

Like:  `cf_units.is_vertical('millibar')` might be always `True`, but
`cf_units.is_vertical('km')` can be vertical or horizontal.

We will use this method to confirm that the units from a **known** vertical coordinate has the correct length or pressure units.

Alternatives would be the horrible names: `is_length_or_pressure()`, `is_valid_vertical_units()`, or `is_valid_vertical()`.

I guess that we could only add a note in the docs then!?

**Comment by rhattersley** [comment]
> Alternatives would be the horrible names: is_length_or_pressure(), is_valid_vertical_units(), or is_valid_vertical().

Or `could_be_vertical()`, `might_be_vertical()`, `is_possibly_vertical()`, ...

**Comment by ocefpaf** [comment]
I knew someone could com up with worse names :wink: 

I read the docs and they are clear enough:

```
Determine whether the unit is a related SI Unit of pressure or distance.
```

My bad for opening this in the first place.  Let's just close it.

**Comment by rhattersley** [comment]
> I knew someone could com up with worse names :wink:

:stuck_out_tongue:
