### ISSUE TITLE
Incompatibility of num2date

### ISSUE THREAD

**Issue by adamcpovey** [SciTools/cf-units#159]
The [description](https://github.com/SciTools/cf-units/blob/a3eeaf15622bd3ec6f23c18cbd3b3658086aa7cf/cf_units/__init__.py#L511) of `cf_units.num2date()` claims that it behaves the same as `matplotlib.dates.num2date()`, which [is](https://github.com/matplotlib/matplotlib/blob/afa8d2821d0189b809ce3fd4ed4beabe5c5f97a8/lib/matplotlib/dates.py#L436) [itself](https://github.com/matplotlib/matplotlib/blob/afa8d2821d0189b809ce3fd4ed4beabe5c5f97a8/lib/matplotlib/dates.py#L304) [a call](https://github.com/matplotlib/matplotlib/blob/afa8d2821d0189b809ce3fd4ed4beabe5c5f97a8/lib/matplotlib/dates.py#L283) to `datetime.datetime.fromordinal()`.

Comparing these calls for day 1,
```python
from cf_units import Unit
from matplotlib.dates import num2date
from datetime import datetime

pg_unit = Unit('days since 001-01-01 00:00:00', calendar='proleptic_gregorian')
print("cfunits.num2date():", pg_unit.num2date(1))
print("matplotlib.dates.num2date():", num2date(1))
print("datetime.datetime.fromordinal():", datetime.fromordinal(1))
```

> cfunits.num2date(): 0001-01-02 00:00:00
> matplotlib.dates.num2date(): 0001-01-01 00:00:00+00:00
> datetime.datetime.fromordinal(): 0001-01-01 00:00:00

The easy answer would be to change the documentation, but I feel like naive use of `num2date()` should replicate the `datetime` behaviour.

**Comment by rcomer** [comment]
Hi @adamcpovey, thanks for raising this.  It seems that `matplotlib`'s behaviour changed at v3.3, and is now more consistent with `cf_units` behaviour:

```python
from cf_units import Unit
from matplotlib.dates import num2date

pg_unit = Unit('days since 1970-01-01 00:00:00', calendar='proleptic_gregorian')
print("cfunits.num2date():", pg_unit.num2date(1))
print("matplotlib.dates.num2date():", num2date(1))
```
gives
```
cfunits.num2date(): 1970-01-02 00:00:00
matplotlib.dates.num2date(): 1970-01-02 00:00:00+00:00
```
However there are still some inconsistencies in that `cf_units` does not have the microsecond precision of `matplotlib`, and `cf_units` does not return a pure `datetime.datetime`.  We decided that setting all this out in the docstring was probably more trouble than it's worth (and more than the average user will want to read) so have simply removed that paragraph in #168.
