### ISSUE TITLE
Change of behaviour due to latest cftime

### ISSUE THREAD

**Issue by duncanwp** [SciTools/cf-units#161]
It seems that the latest version of `cftime` always returns cftime objects, which means that the cf-units documentation is no longer correct and the default behaviour has changed.

Specifically, the `only_use_cftime_datetimes` option in `cftime.num2date` defaults to `True`. I would argue that the cf-units call to this function should set this to be `False` for the meantime to maintain the current documented expectation that it should return python datetimes where possible. In a future major release it would be better to allow this option (and the accompanying `only_use_python_datetimes` option) to be passed down the call stack.

**Comment by trexfeathers** [comment]
Hi @duncanwp, I've requested some time within my team (which includes several `cf-units` contributors) to take a look at this. But it's difficult to tell when this will happen, so feel free to put up a PR if you have the time 🙂

**Comment by duncanwp** [comment]
Hi @trexfeathers thanks for picking this up! As fas as I can tell this will affect all calls to `cftime.num2date`. For example:
```
>>> print(type(cf_units.num2date(100, 'seconds since 1900-01-01', 'gregorian')))
<class 'cftime._cftime.real_datetime'>
```
Whereas this should be a `datetime.datetime`.
