### ISSUE TITLE
cf-units breaks with update of cftime to 1.5.0

### ISSUE THREAD

**Issue by zklaus** [SciTools/cf-units#170]
cftime 1.5.0 has now removed utime and cf-units breaks. I suggest to make a bug fix release that limits the supported version in requirements to cftime <1.5.0 and then to move forward with the removal per @rcomer's PR.

**Comment by trexfeathers** [comment]
cf-units `v3.0.0` works with cftime `v1.5` and is available on PyPI and Anaconda 👍
