### ISSUE TITLE
Cython?

### ISSUE THREAD

**Issue by rhattersley** [SciTools/cf-units#18]
It might tidy things up a bit to use Cython for the bindings to UDUNITS.

It might also enable the path to UDUNITS to be baked in at compile time, thus avoiding the need for configuration when using conda.

I believe @marqh has done some prior experimenting in this space.

**Comment by ocefpaf** [comment]
I also found this project that might help moving this forward:

https://github.com/ckhroulev/py_udunits2

**Comment by pelson** [comment]
Closed by #71
