### ISSUE TITLE
Importing _udunits2 on Google Colab

### ISSUE THREAD

**Issue by mg725** [SciTools/cf-units#188]
### Discussed in https://github.com/SciTools/cf-units/discussions/187

<div type='discussions-op-text'>

<sup>Originally posted by **mg725** July 12, 2021</sup>
Hi, I am currently trying to use Iris within Google Colab. I have managed to install it through Conda, however I am struggling to import it - when I do, the following error message is returned:

ImportError                               Traceback (most recent call last) <ipython-input-24-089b5db944e7> in <module>() ----> 1 import iris
6 frames
/usr/local/lib/python3.6/site-packages/cf_units/__init__.py in <module>()      43 from .util import _OrderedHashable, approx_equal      44  ---> 45 from cf_units import _udunits2 as _ud      46 from cf_units._udunits2 import (UT_ASCII, UT_ISO_8859_1, UT_LATIN1, UT_UTF8,      47                                 UT_NAMES, UT_DEFINITION) ImportError: cannot import name '_udunits2' from 'cf_units' (/usr/local/lib/python3.6/site-packages/cf_units/__init__.py)

The problem seems to be that Google Colab is struggling to import _udunits2 from cf_units. I have checked and both these packages are installed on Google Colab and so I can't understand why they won't import.

Does anyone have any ideas of how to get round this issue? Thanks very much in advance if you can help out at all!</div>

**Comment by trexfeathers** [comment]
[The latest cf-units does not provide a Python 3.6 build](https://anaconda.org/conda-forge/cf-units/files?version=3.0.1), so Conda must have installed an older version in your case. Are you able to recreate your project with Python 3.7 or 3.8?

**Comment by rcomer** [comment]
Hi @mg725, did you get it working with a newer python version?  If not, perhaps you can share your notebook so we can see exactly what you are doing.

**Comment by bjlittle** [comment]
I'm going to close this issue, as sadly I think it's gone stale.

Please feel free to re-open it @mg725 and we can re-investigate if this is still a live issue for you.

Thanks :+1:
