### ISSUE TITLE
PyPI release

### ISSUE THREAD

**Issue by ocefpaf** [SciTools/cf-units#25]
@rhattersley and @pelson do you to upload to PyPI as SciTools or do you want me to do it as an user?

PS: I just sent my first PR to another project using `cf_units` (https://github.com/ioos/compliance-checker/pull/110).

**Comment by rhattersley** [comment]
We upload to PyPI with our own personal accounts, so you're very welcome to do the upload as you. We can easily add additional package maintainers/owners afterwards.

**Comment by ocefpaf** [comment]
OK. I will do it.

Thanks @rhattersley!

**Comment by ocefpaf** [comment]
And done: https://pypi.python.org/pypi/cf_units/0.1.0

**Comment by rhattersley** [comment]
Nice work @ocefpaf :tada:

**Comment by rhattersley** [comment]
The links in the README.md file aren't rendering properly. FWIW, Biggus & Cartopy both use a `README.rst`.

**Comment by ocefpaf** [comment]
Ops, I fixed the badge but forgot the link at the bottom.  (See PR #26).  I already re-registered on PyPI with the fix.
