### ISSUE TITLE
Align long time interval check with cftime

### ISSUE THREAD

**Issue by trexfeathers** [SciTools/cf-units#274]
We currently blanket disallow `month` or `year` intervals when passing operations down to cftime:

https://github.com/SciTools/cf-units/blob/37c840008a12e6f8495ebf400c7c7839cab173f1/cf_units/__init__.py#L1932-L1939

cftime disallows these intervals, presumably because it requires consistent-length time increments. But cftime is more intelligent about this than cf-units is, e.g. `month` intervals are allowed for `360_day` calendars (Unidata/cftime#75).

We should make sure our own checks don't cover over details like the `360_day` exception. The Pythonic choice would be to do no extra checks at all in cf-units, simply relying on cftime to raise the appropriate error; is there a good reason why we don't do this?

**Comment by rcomer** [comment]
Looks like the decision was made in cf-units _ages_ ago #72.  Seems sensible to revisit.
