### ISSUE TITLE
Copyright and License

### ISSUE THREAD

**Issue by lukecampbell** [SciTools/cf-units#29]
What is the license on this project? I see GPL v3 but I also see a Crown Copyright which is all rights reserved, I believe.  

Is there anyway that this project could be licensed under LGPL or something less restrictive than GPL?

**Comment by rhattersley** [comment]
> What is the license on this project?

LGPL v3

> I see GPL v3

Having both `COPYING` and `COPYING.LESSER` can be confusing. But according to the [GNU guidance](https://www.gnu.org/licenses/gpl-howto.html) we need both "since the LGPL is a set of additional permissions on top of the GPL, it's important to include both licenses".

**Comment by rhattersley** [comment]
> I also see a Crown Copyright which is all rights reserved, I believe.

The copyright is not incompatible with the LGPL. The GNU guidance mentioned above describes how you need to have the copyright declaration.

**Comment by lukecampbell** [comment]
Sorry, yeah I missed the COPYING.lesser, but the project README still has an implied all rights reserved copyright instead of the LGPL Preamble?

**Comment by ocefpaf** [comment]
@rhattersley `cf_units` and `iris` have only _(C) British Crown Copyright 2010 - 2014, Met Office_ in the README.  Do you want me to add a few lines at the end?  Cartopy, for example, has the following text:

```
----
Code
----
Cartopy is licenced under GNU Lesser General Public License (LGPLv3).
Development occurs at https://github.com/SciTools/cartopy.
```

**Comment by lukecampbell** [comment]
As long as it's noted somewhere what the license is in the project. Right now, I believe, there are conflicting Copyrights. The README has a Crown Copyright which is like the USC 17 Copyright and is automatically "All rights reserved." But the license file is LGPL 3. 

If it's not too much bother could you update the README, you can keep the Crown copyright notice but under it add the rest of the LGPL from the LGPL guidance (COPYING.LESSER should have it).

**Comment by ocefpaf** [comment]
PR #26 will add that to the PyPI classifiers.  I can also add

```
----
Code
----
cf_units is licenced under GNU Lesser General Public License (LGPLv3).
Development occurs at https://github.com/SciTools/cf_units.
```

to the README.  What do you think @rhattersley?

**Comment by rhattersley** [comment]
> Right now, I believe, there are conflicting Copyrights.

The copyright/licence combination is as specified by our legal team - there is no known conflict.

It's important to remember that the copyright is distinct from the licence, and the copyright  headers in the project do not go on to add "all rights reserved". Note the existence of the [Open Government Licence](http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/) which also allows publication of material under the Crown Copyright.

> What do you think @rhattersley?

Looks good to me. :+1: For completeness, it'd be good to mention that the full text of the licence can be found in the COPYING and COPYING.LESSER files.

**Comment by ocefpaf** [comment]
@lukecampbell PR #26 should sorted this out.  Let me know if you still need anything.

**Comment by lukecampbell** [comment]
Beautiful, thanks!
