### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by ocefpaf** [SciTools/cf-units#3]
Copy all documentation related to `units` here.

**Comment by pelson** [comment]
Perhaps we can use readthedocs for hosting.

**Comment by DPeterK** [comment]
Docs are available in the wild: http://scitools.org.uk/cf_units/index.html

> Perhaps we can use readthedocs

I seem to remember putting some effort into that, but encountering some problems getting cf_units to build on readthedocs servers...

**Comment by bjlittle** [comment]
It would be great to get some time to sort this out. The docs need some :heart:
