### ISSUE TITLE
CF valid units that are not in UDUNITS

### ISSUE THREAD

**Issue by mhidas** [SciTools/cf-units#30]
The [CF FAQ](http://cfconventions.org/faq.html#udunits_missing) page says:

> There are two units acceptable to CF that are not in the UDUNITS library: **sverdrup**, and **decibel** or **dB**. These have been requested for inclusion in future versions of the UDUNITS library.

Looks like "sverdrup" is already in UDUNITS-2. "decibel" and "dB" are not. There is an open request to add it (https://github.com/Unidata/UDUNITS-2/issues/33), but the discussion there suggests this may not be possible in a generic way, i.e. without specifying a reference value.

Would it be possible to get cf_units to recognise "dB" and "decibel" (as effectively dimensionless units), independently of UDUNITS?

**Comment by ocefpaf** [comment]
Thanks for reporting this @mhidas.

`cf_units` goal is to be CF compliant, so we should try to include those.  I will see what we can do and get back to you.

**Comment by rhattersley** [comment]
FYI, @hasselldc ships a [modified UDUNITS database](https://bitbucket.org/cfpython/cf-python/src/94ffc37103271fdcb2d7f00816777ecba13f488c/cf/etc/udunits/?at=master) in cf-python.

**Comment by ocefpaf** [comment]
Thanks @rhattersley!  I will take a look and, if possible, push it upstream to UDUNITS-2.

**Comment by ocefpaf** [comment]
- [ ] level
- [ ] layer
- [ ] sigma_level
- [ ] decibel, dB

**Comment by ocefpaf** [comment]
Note to self: https://github.com/Unidata/UDUNITS-2/pull/42

**Comment by mhidas** [comment]
Has there been any progress on this issue?

I don't think any of these units will make it into UDUNITS any time soon, if the (lack of) activity in those issue threads (https://github.com/Unidata/UDUNITS-2/issues/33, https://github.com/Unidata/UDUNITS-2/pull/42) is anything to go by.

**Comment by pelson** [comment]
> Has there been any progress on this issue?

It doesn't appear so. https://github.com/Unidata/UDUNITS-2/pull/42 does look promising. Adding custom udunits definitions is also an option. Given the relevance of the CF documentation, if you have a proposal for moving this forwards without adding significant complexity to ``cf_units`` then I can't see that it would be a problem to merge.

**Comment by mhidas** [comment]
Thanks @pelson . I've commented on that UDUNITS PR to see if there's a chance of getting it merged. If there's no response I'll look into proposing a solution here.

**Comment by trexfeathers** [comment]
@ocefpaf sorry for gravedigging but https://github.com/Unidata/UDUNITS-2/pull/42 was finally merged last year. Any thoughts on this issue?

**Comment by ocefpaf** [comment]
We can backport it as a patch but I'd rather ask upstream for a new release. The latest one is https://github.com/Unidata/UDUNITS-2/releases/tag/v2.2.27.27 from Nov 20, 2020 and that PR (from 2016!) was merged on [Mar 17, 2021](https://github.com/Unidata/UDUNITS-2/pull/42#event-4470674675).

**Comment by stephenworsley** [comment]
It looks like the last release was Feb 1st 2022 but this was not tagged https://github.com/Unidata/UDUNITS-2/issues/104. So it looks like this ought to be in a released version.

**Comment by larsbarring** [comment]
Please note that the [CF FAQ text](https://cfconventions.org/faq.html#are-there-units-in-cf-that-arent-in-udunits) referred to in the opening comment is not up to date.

**Comment by trexfeathers** [comment]
From @SciTools/peloton, can this be:

A: closed?
B: progressed?
C: re-assigned if @ocefpaf is busy?

**Comment by ocefpaf** [comment]
I had no idea it was assigned to me :-)
I vote for A and, if folks really need this, someone will re-open the issue and/or send a PR. My guess is that most downstream Software that requires these units end up patching and/or adding them via a custom xml file.
