### ISSUE TITLE
Python 3?

### ISSUE THREAD

**Issue by rabernat** [SciTools/cf-units#31]
I tried to install this with python 3.4. It installed fine, but I got the following runtime error after calling `import cf_units`

```
ImportError: No module named 'ConfigParser
```

Am I correct in assuming that the package is python 2 only?

**Comment by ajdawson** [comment]
Essentially. I think Python 3 support is incomplete but is being worked on currently, see PR #22. I don't know what the status of that branch is right now, perhaps @ocefpaf or @qulogic can answer that.

The cf_units project is a stand-alone version of the units code in [iris](https://github.com/SciTools/iris), which is also moving towards Python 3 support, so I'd expect cf_units to be Python 3 compatible in the near future.

**Comment by ocefpaf** [comment]
@rabernat as @ajdawson mentioned Python 3 is a working in progress.  I still need to catch-up with @qulogic changes in iris.  Hopefully I will be able to get back to this next weekend.

**Comment by rabernat** [comment]
You're a busy man @ocefpaf! The reason I am here is because of xray/xray#523.

**Comment by ocefpaf** [comment]
@rabernat py3k is finally ready! 

http://anaconda.org/IOOS/cf_units/files

Hope that is useful for you.  Let me know if you find any issues.
