### ISSUE TITLE
Build as conda and upload to binstar

### ISSUE THREAD

**Issue by rsignell-usgs** [SciTools/cf-units#4]

**Comment by ocefpaf** [comment]
Not sure if it is a good idea.  There will be several changes until this package takes its final form.  
Anyways, I created [one](https://github.com/ioos/conda-recipes/pull/114)  :smiling_imp:.  But I do not recommend its use in production :unamused: right now

PS: [Here](http://nbviewer.ipython.org/gist/ocefpaf/60ecac928612f5ae8fed) is a comparison between this package and `udunitspy`.

**Comment by ocefpaf** [comment]
@rsignell-usgs now that we have a name it is OK to merge PR https://github.com/ioos/conda-recipes/pull/115.
