### ISSUE TITLE
360 day calendar converting 1 hour to 59 minutes and 59 seconds

### ISSUE THREAD

**Issue by hdyson** [SciTools/cf-units#46]
Converting 1 hour to a date using num2date gives different results depending on the calendar:

``` python
>>> import cf_units
>>> unit_gregorian = cf_units.Unit('hours since 1970-01-01 00:00:00', calendar='gregorian')
>>> print(unit_gregorian.num2date(1))
1970-01-01 01:00:00
>>> unit_360 = cf_units.Unit('hours since 1970-01-01 00:00:00', calendar='360_day')
>>> print(unit_360.num2date(1))
1970-01-01 00:59:59
```

I'd expect the behaviour from the 360 day calendar to be consistent with that of the gregorian calendar.

Update:  I see the correct behaviour with netCDF4-python v1.0.2, but the incorrect behaviour with netCDF4-python v1.2.1, so this may be an issue with the underlying library.

**Comment by pelson** [comment]
> Update: I see the correct behaviour with netCDF4-python v1.0.2, but the incorrect behaviour with netCDF4-python v1.2.1, so this may be an issue with the underlying library.

Thanks for the update @hdyson. We should definitely track this - did you raise it at https://github.com/Unidata/netcdf4-python?

**Comment by pelson** [comment]
This was fixed upstream in cftime (sorry, I don't have the commit that did it):

```
In [6]: unit_360 = cf_units.Unit('hours since 1970-01-01 00:00:00', calendar='360_day')                                                                              

In [7]: print(unit_360.num2date(1))                                                                                                                                  
1970-01-01 01:00:00
```
