### ISSUE TITLE
BUG: Non cf_units handling results in information loss

### ISSUE THREAD

**Issue by cpelley** [SciTools/cf-units#47]
Function at issue [here](https://github.com/SciTools/cf_units/blob/e23abea58c878a8cb6bb018048da7e6bb6a146ff/cf_units/__init__.py#L764)

Context for the conditions where the behaviour of this function result in a loss in information is described here:
https://github.com/SciTools/iris/issues/1874

**Comment by pelson** [comment]
Thanks @cpelley. Are you interested in having a go at fixing the issue?

**Comment by cpelley** [comment]
Sure

**Comment by DPeterK** [comment]
The fix for this got merged like ages ago, so I'm going to close this.
