### ISSUE TITLE
Release v1.1.0

### ISSUE THREAD

**Issue by pelson** [SciTools/cf-units#50]
There are a few commits since v1.0.0: https://github.com/SciTools/cf_units/compare/v1.0.0...master
I've created a v1.1.0 milestone. All we need to do is tag the release (we have versioneer on our side now) and push some docs somewhere(?).

**Comment by cpelley** [comment]
@pelson, do you have an expected timescale for the release? (just figuring out when I need to complete #47).

**Comment by pelson** [comment]
> do you have an expected timescale for the release?

Not especially - the sooner the better, but inevitably these things slip. The good news is that it is trivial to release, so releases are quick and cheap.

**Comment by daf** [comment]
Seems like this was [released already](https://github.com/SciTools/cf_units/releases/tag/v1.1).  Could you folks upload to PyPI please?

**Comment by bjlittle** [comment]
@daf et al Pushed the sdist for [v1.1.1](https://pypi.python.org/pypi/cf_units/1.1.1) up to PyPI
