### ISSUE TITLE
Iris copyright in cf_units/tests/unit/__init__.py

### ISSUE THREAD

**Issue by pelson** [SciTools/cf-units#52]
There is mention of Iris in `cf_units/tests/unit/__init__.py` which isn't strictly correct.

**Comment by QuLogic** [comment]
The GitHub description also references Iris:
![screenshot from 2016-04-21 23-19-53](https://cloud.githubusercontent.com/assets/302469/14730774/971c3ca4-0817-11e6-9cd5-fb42c2f92dd5.png)

**Comment by rhattersley** [comment]
> The GitHub description also references Iris:

Thanks - I've updated it to use the first line of the readme.

**Comment by marqh** [comment]
this issue looks like it is all dealt with now, so I am closing it
