### ISSUE TITLE
Rename the package

### ISSUE THREAD

**Issue by ocefpaf** [SciTools/cf-units#7]
@ChrisBarker-NOAA let s move the discussion here.

> Maybe "cf_units" it's all about CF, but theoretically only used by Iris, rather than the other way around. But I don't care, really. Good to have "units" in the name, so people will find it.

I like `cf_units`.  @rsignell-usgs what do you think?  However, it has to be a name that iris devs are fine with.  The goal is to aggregate efforts in one package instead of fragmenting it.

> @ocefpaf : maybe udinits2 could be built-in, rather then kept as a separate package. It would make it harder to build, but then it would be only one package to manage.

Right now, we have udunits2 on conda for Linux, Windows and Mac (thanks to you :smile: ), so that is not a big issue.  Also, my Linux packager side is biased against it...  I like to see small packages with proper dependencies :grin:

**Comment by rsignell-usgs** [comment]
I like `iris_units` or `cf_units` equally well.   Let's see what @rhattersley and @pelson have to say?

**Comment by pelson** [comment]
I don't think it needs to be named `iris_*` - I like `cf_units` as a descriptive name - @rhattersley tends to be pretty creative with names if you want it to be non-descriptive :wink:.

> The goal is to aggregate efforts in one package instead of fragmenting it.

I whole-heatedly buy into this perspective. There is room under the scitools organisation for this to be hosted (i.e. `github.com/scitools/cf_units`) if that is where you want to go - I'd happily add my support for @ocefpaf to be given core developer status of that repository along with the existing @scitools devs.

Thoughts?

**Comment by rhattersley** [comment]
:+1: for `cf_units` :smile:

... with the proviso that this package is intending to provide _CF_ units support, as opposed to just a Python wrapper for UDUNITS-2. For example, it might aspire to support `level`, `layer`, and `sigma_level` in some fashion, or ensure that "scale factors and offsets [are] not supported".

(It might be worth seeing if [the corresponding functionality](http://cfpython.bitbucket.org/docs/0.9.9/classes/cf.Units.html) from cf-python can be folded in and shared. @hasselldc?)

**Comment by ocefpaf** [comment]
`cf_units` it is.  (For a moment there I thought @rhattersley would suggest for Biggus D. friend N. Maximus!)

> @ocefpaf to be given core developer status of that repository along with the existing @scitools devs.

I'd love to see this at `github.com/scitools/cf_units`.

@pelson I don't think I have the coding knowledge nor experience to be a @scitools dev, but I will do my best to maintain and move `cf_units` forward.

> For example, it might aspire to support `level`, `layer`, and `sigma_level` in some fashion, or ensure that "scale factors and offsets [are] not supported".

Make sense #8.

**Comment by rhattersley** [comment]
> I'd love to see this at github.com/scitools/cf_units.

@ocefpaf - Following the [GitHub help](https://help.github.com/articles/transferring-a-repository/#transferring-from-a-user-to-an-organization), I've sent you an invite to join the SciTools org. That should enable you to transfer the repo if you so wish.

> For a moment there I thought @rhattersley would suggest for Biggus D. friend N. Maximus!

Drat! I didn't think of that! :wink:

**Comment by ocefpaf** [comment]
> That should enable you to transfer the repo if you so wish.

Done.
