### ISSUE TITLE
Problem with unit convertion with calendar='360_day'

### ISSUE THREAD

**Issue by ehogan** [SciTools/cf-units#70]
```
Python 2.7.12 | Met Office - SciTools | (default, Sep 22 2016, 17:01:57) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-3)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cf_units
>>> my_unit = cf_units.Unit('years', calendar='360_day')
>>> print my_unit.convert(1, 'seconds')
31556925.9747
>>> 
```
Shouldn't this be 60 * 60 * 24 * 360 = 31104000?

**Comment by pp-mo** [comment]
You should not use any units based on ‘years’ or ‘months’, because while udunits2 does have such things their meaning is profoundly unexpected and almost universally unhelpful !
See : http://cfconventions.org/cf-conventions/v1.6.0/cf-conventions.html#time-coordinate
Where it says ...
> We recommend that the unit year be used with caution. The Udunits package defines a year to be exactly 365.242198781 days (the interval between 2 successive passages of the sun through vernal equinox). It is not a calendar year. Udunits includes the following definitions for years: a common_year is 365 days, a leap_year is 366 days, a Julian_year is 365.25 days, and a Gregorian_year is 365.2425 days.
> 
> For similar reasons the unit month, which is defined in udunits.dat to be exactly year/12, should also be used with caution.

So, quite a gotcha !
Does that help ?

**Comment by ehogan** [comment]
Yes, thank you very much! :)

**Comment by ajdawson** [comment]
The underlying reason for this is that calendars are only respected when you use a relative unit containing the word `'since'` (e.g. `'days since 1900-01-01'`). The `Unit` constructor is deliberately ignoring your calendar specification because it can't use it.

**Comment by ehogan** [comment]
Thanks for the additional information! :)
