### ISSUE TITLE
cf_units breaks day_of_year for 360_day calendars

### ISSUE THREAD

**Issue by pp-mo** [SciTools/cf-units#81]
Here's the problem :
```
>>> import cf_units
>>> import netcdftime
>>> nc_calendar_360day = netcdftime.utime('hours since 1970-01-01', calendar='360_day')
>>> cf_unit_360day = cf_units.Unit('hours since 1970-01-01', calendar='360_day')
>>> print nc_calendar_360day.num2date(232560.5).timetuple()
(1996, 12, 1, 0, 30, 0, -1, 331, -1)
>>> print cf_unit_360day.num2date(232560.5).timetuple()
(1996, 12, 1, 0, 30, 0, -1, 1, -1)
>>> 
```

Those two answers ***ought*** to be the same,
( especially as the time-of-day is nowhere near midnight )

The basic problem is that [this call](https://github.com/SciTools/cf_units/blob/v1.1.3/cf_units/__init__.py#L715) is not in fact a suitable object constructor call :  the [`netcdftime.datetime.__init__()` interface](https://github.com/Unidata/netcdftime/blob/c70a2dffb1f0e0d9dd570fc759a1c54d9463e8b0/netcdftime/_netcdftime.pyx#L1486) seems designed only for object copying, and an unspecified day-of-year defaults to 1 rather than being calculated from date + calendar as you might reasonably expect.

It's a wee bit awkward because there is no real API specced for these classes :-(
It's a live issue :  https://github.com/Unidata/netcdftime/issues/3

**Comment by pp-mo** [comment]
Thought : would [the `netcdftime.datetime.replace()` function](https://github.com/Unidata/netcdftime/blob/c70a2dffb1f0e0d9dd570fc759a1c54d9463e8b0/netcdftime/_netcdftime.pyx#L1512) help ?

Should work I think, if the `datetime.datetime.replace()` call is compatible

**Comment by duncanwp** [comment]
I think I've hit a related issue. 

The following code:
```
import iris
cube = iris.load_cube(iris.sample_data_path("A1B_north_america.nc"))
tcoord = cube.coord('time')

def since_1980(cell):
    return tcoord.units.num2date(cell.point).year >= 1980

cube = cube.extract(iris.Constraint(time=since_1980))
```

used to work fine (and is a solution to one of the Iris course examples), but now throws:

```
...
<ipython-input-7-bfb649a13943> in since_1980(cell)
      2 
      3 def since_1980(cell):
----> 4     return tcoord.units.num2date(cell.point).year
      5 
      6 tcon = iris.Constraint(time=since_1980)

~/miniconda3/envs/cis_env_iris2/lib/python3.6/site-packages/cf_units/__init__.py in num2date(self, time_value)
   1987         """
   1988         cdf_utime = self.utime()
-> 1989         return _num2date_to_nearest_second(time_value, cdf_utime)

~/miniconda3/envs/cis_env_iris2/lib/python3.6/site-packages/cf_units/__init__.py in _num2date_to_nearest_second(time_value, utime)
    599     # later versions, if one wished to do so for the sake of consistency.
    600     has_half_seconds = np.logical_and(utime.units == 'seconds',
--> 601                                       time_values % 1. == 0.5)
    602     dates = utime.num2date(time_values)
    603     try:

TypeError: unsupported operand type(s) for %: 'cftime._cftime.Datetime360Day' and 'float'
```

**Comment by pelson** [comment]
@duncanwp - first impression is that this isn't related. My reading of what you've got there is a solution that was necessary in Iris 1, but which changed when cell dateteimes became default in Iris 2. Essentially, I don't think you need to do anything in that function other than ``return cell.point.year >= 1980``.

**Comment by pelson** [comment]
That said, maybe we should capture the fact that num2date doesn't support datetimes as an input....

**Comment by pelson** [comment]
@pp-mo - is there something that cf-units is doing wrong here, or should we be moving this issue up to cftime?

**Comment by pp-mo** [comment]
> @pelson  is there something that cf-units is doing wrong here, or should we be moving this issue up to cftime?

I think the cf_units code is actually *wrong*, as stated [above](https://github.com/SciTools/cf-units/issues/81#issue-271034708) where it says ...
""The basic problem is that   [this call](https://github.com/SciTools/cf_units/blob/v1.1.3/cf_units/__init__.py#L715) is not in fact a suitable object constructor call ""

The question is how can you do this in a stable way, as I think the cftime API is rather unclear.
We need to make a slightly-modified "copy" of the argument, but the cftime class constructor is a bit of a problem as it is not compatible with that for ['normal' datetimes](https://docs.python.org/2/library/datetime.html#datetime-objects)  --  possibly this is what changed ?

@dkillick suggested (offline) that we can instead try copying the dates and then setting microseconds to 0.  Unfortunately I can't afford the time to investigate that now.

**Comment by pelson** [comment]
Fixed with use of ``cftime``:

```
In [1]: import cf_units 
   ...: import cftime 
   ...:  
   ...:  
   ...: cf_unit_360day = cf_units.Unit('hours since 1970-01-01', calendar='360_day') 
   ...: nc_calendar_360day = cftime.utime('hours since 1970-01-01', calendar='360_day')                                                                              
                                                                                                                                                    

In [2]: print(nc_calendar_360day.num2date(232560.5).timetuple()) 
   ...: print(cf_unit_360day.num2date(232560.5).timetuple())                                                                                                         
time.struct_time(tm_year=1996, tm_mon=12, tm_mday=1, tm_hour=0, tm_min=30, tm_sec=0, tm_wday=4, tm_yday=331, tm_isdst=-1)
time.struct_time(tm_year=1996, tm_mon=12, tm_mday=1, tm_hour=0, tm_min=30, tm_sec=0, tm_wday=4, tm_yday=331, tm_isdst=-1)
```
