### ISSUE TITLE
Tarball MD5 Checksums are Unstable

### ISSUE THREAD

**Issue by citibeth** [SciTools/cf-units#87]
@pelson At Spack (an auto-installer), we use MD5 checksums to verify the integrity of downloaded tarballs before we installed.  We're having trouble with `cf_units` because its MD5 checksums are not stable.  Would you be able to please take a look at https://github.com/spack/spack/issues/7937 and see if there' something that could be done about it on the `cf_units` end?

**Comment by pelson** [comment]
Hi @citibeth. Thanks for the great writeup in the linked issue. I've responded in https://github.com/spack/spack/issues/7937#issuecomment-385979160.

From the above conversation, I think there isn't much that we can do at cf-units beyond ensuring that we merge our release branches back into master asap after tagging. I'm almost tempted to write a bot that does that for us (and everybody else who uses the release-branch concept).

I hope that is a reasonable compromise?

**Comment by citibeth** [comment]
Yes works for me!
