### ISSUE TITLE
v2 release

### ISSUE THREAD

**Issue by pelson** [SciTools/cf-units#95]

**Comment by pelson** [comment]
The config options for cf_units have changed - we no longer listen to the site.cfg for the libudunits.so.

**Comment by ocefpaf** [comment]
We have a stable release of `cftime`, see https://github.com/Unidata/cftime/issues/46, it is available on `conda-forge` and `PyPI`. It would be nice to get `cf_units 2.0` out too.

**Comment by pelson** [comment]
Wowzers. That was good timing. I've just tagged v2... https://github.com/SciTools/cf_units/releases/tag/v2.0.0.

**Comment by pelson** [comment]
🎉

**Comment by pelson** [comment]
https://pypi.org/project/cf_units/

**Comment by pelson** [comment]
@ocefpaf - want to do conda-forge or shall I?

**Comment by ocefpaf** [comment]
Yep. I have a PR ready :wink:

**Comment by pelson** [comment]
For the record: https://github.com/conda-forge/cf_units-feedstock/pull/14
