### ISSUE TITLE
Creating a cf_units.Array

### ISSUE THREAD

**Issue by pelson** [SciTools/cf-units#96]
Given how much better numpy is at allowing arrays to be subclassed than it used to be, I wonder if we should consider doing so for this package...

Proposed API:

```
>>> import numpy as np
>>> import cf_units

# Unit is a *mandatory* keyword only kwarg.
>>> x = cf_units.Array(np.arange(10), unit='meters')
>>> y = cf_units.Array(np.arange(10), unit='meters')

>>> print(x)
[0 1 2 3 4 5 6 7 8 9] m

>>> print(repr(x))
cf_units.Array([0 1 2 3 4 5 6 7 8 9], unit='meters')

>>> print(f'{x.mean()}{x.units}')
4.5m

>>> print(x * y)
[ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81] m2

>>> print(type(x*y))
cf_units.Array
```

The challenge with implementing this appears to be in figuring out a scheme that works for both ``np.ndarray`` and ``da.ndarray``.

cc @dopplershift as somebody with history here 😉

**Comment by dopplershift** [comment]
While I want the functionality, I’m not sure the world needs another ndarray unit library. @ngoldbaum has separated out Yt’s unit support in [unyt](https://github.com/yt-project/unyt), so I wonder if it would be better to rely on it and maybe just handle the CF-specific parsing here or there.

**Comment by ngoldbaum** [comment]
FWIW, parsing cf-compliant data is within the scope of our NSF grant, so this is something that will need to be added to `unyt` eventually.

**Comment by pelson** [comment]
> parsing cf-compliant data is within the scope of our NSF grant

What is surprising about cf-compliant units is that the CF spec literally defers to UDUNITS...

http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#units

> The value of the units attribute is a string that can be recognized by UNIDATA’s Udunits package [UDUNITS], with a few exceptions that are given below.

Are you therefore planning to wrap UDUNITS?

----

> While I want the functionality, I’m not sure the world needs another ndarray unit library.

That's why I pinged you 😉. 

cf-units serves a definite purpose today, so we aren't talking about another *library* per-se, we're talking about an improved interface for the existing capabilities. I suspect we will be able to push a bunch of functionality out of Iris and into cf-units if we were to have a smart array-based representation of ``[lazy]array+unit``, which could be win-win for all...

**Comment by ngoldbaum** [comment]
> Are you therefore planning to wrap UDUNITS?

Apologies if I was imprecise in my comment yesterday. I merely meant that `unyt` needs to eventually understand cf-compliant units. That will probably mean wrapping `cf-units`.

**Comment by dopplershift** [comment]
@pelson I don't know how much useful functionality you already have in iris. It just seems to me that it would be nice if we could all share one common implementation of `__array_ufunc__`, indexing machinery, lazy handling, etc. rather than dividing our forces and our ability to do maintenance. It seems wrong to cf_unit and unyt both implement all of this machinery.

**Comment by pelson** [comment]
> It seems wrong to cf_unit and unyt both implement all of this machinery.

Yes, I agree completely. I've actually got quite a long way towards hacking with numpy to see how much I can bend the dtype concept... The following isn't *quite* yet implemented, but I'm not that far off:

```
>>> a = np.array([10, 20], dtype=cf_units.Unit('meters').dtype('float64'))
>>> print(a)
np.array([10., 20.], dtype=cf_units.Unit('meters').dtype('float64'))

>>> print(a + 10)
np.array([20., 30.], dtype=cf_units.Unit('meters').dtype('float64'))

>>> print(a + cf_units.Unit('km').dtype('float64').type(10))
np.array([10010., 10020.], dtype=cf_units.Unit('m').dtype('float64'))

```

Of course, this is ugly as anything, but interesting none-the-less. Plus, I've learnt a ton of stuff about numpy's internals 😉.


I'm in no rush to push with the unit array concept within cf_unit - if we can vendor some of that out without losing the CF-units semantics, I'm game (and able to help with any logistics that may need to happen).

**Comment by ngoldbaum** [comment]
FWIW, we've released unyt on pypi and submitted a paper about it to JOSS.

**Comment by dopplershift** [comment]
@pelson I'm curious exactly *how* close you are on the dtype thing; this would pave the way to something that works with numpy **and** dask I think.

**Comment by pelson** [comment]
> @pelson I'm curious exactly how close you are on the dtype thing; this would pave the way to something that works with numpy and dask I think.

Mmmhhh, that was my thinking too. On the whole, writing an array subclass is far easier and as a result, likely to result in far more predictable results. The downside is integration with tools like dask.

I'm well and truly in this space though as I've been looking at ``geometry`` dtypes (think Shapely + numpy), so I'll be keeping the dtype idea in mind.

In terms of how much is left, I'm probably at the 40% mark, and I'm confident that there is a long tail of development that remains. Not least, figuring out "casting" rules when it comes to combining units with metadata. Probably a good one to play with a bit more at SciPy this year 😉.

> FWIW, we've released unyt on pypi and submitted a paper about it to JOSS.

Nice. I've had a quick look and it looks pretty neat. Have you thought about how something like ``cf-units`` might integrate?

With regards to interoperability, perhaps we should start talking about a standard interface. The [``__geo_interface__``](https://gist.github.com/sgillies/2217756) has been remarkably useful/successful for separating concerns into separate packages. Maybe we should have a ``.__unit__()`` interface/protocol...

**Comment by trexfeathers** [comment]
This has gone stale, and perhaps is now possible via other packages? If nobody shows any further desire for this by 2022-08-31 I'll go ahead and close the issue.

**Comment by rcomer** [comment]
> If nobody shows any further desire for this by 2022-08-31 I'll go ahead and close the issue.

👀
